FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
COMPATIBLE_MACHINE:radxa-cm3-io = "radxa-cm3-io"
COMPATIBLE_MACHINE:radxa-e25 = "radxa-e25"
COMPATIBLE_MACHINE:rock-3a = "rock-3a"
COMPATIBLE_MACHINE:rock-5a = "rock-5a"
COMPATIBLE_MACHINE:rock-5b = "rock-5b"
SRC_URI:append:radxa-cm3-io = " file://rockchip-kmeta;type=kmeta;name=rockchip-kmeta;destsuffix=rockchip-kmeta"
SRC_URI:append:radxa-e25 = " file://rockchip-kmeta;type=kmeta;name=rockchip-kmeta;destsuffix=rockchip-kmeta"
SRC_URI:append:rock-3a = " file://rockchip-kmeta;type=kmeta;name=rockchip-kmeta;destsuffix=rockchip-kmeta"
SRC_URI:append:rock-5a = " file://rockchip-kmeta;type=kmeta;name=rockchip-kmeta;destsuffix=rockchip-kmeta"
SRC_URI:append:rock-5b = " file://rockchip-kmeta;type=kmeta;name=rockchip-kmeta;destsuffix=rockchip-kmeta"
